// <copyright file="ResultsTemplates.cs" author="Ulf Bourelius">
// Copyright (c) 2025 Ulf Bourelius. All rights reserved.
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

using Zentient.Analyzers.Stubs;

namespace Zentient.Analyzers.Templates
{
    /// <summary>
    /// Template builder for generating compilable source for Results analyzer tests.
    /// </summary>
    public sealed class ResultsTemplateBuilder : TemplateBuilder<ResultsTemplateBuilder>
    {
        protected override string Usings =>
        @"// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Diagnostics.CodeAnalysis;
using System.Reflection.Metadata;

using Zentient.Abstractions.Codes;
using Zentient.Abstractions.Codes.Definitions;
using Zentient.Abstractions.Common;
using Zentient.Abstractions.Common.Definitions;
using Zentient.Abstractions.Errors;
using Zentient.Abstractions.Errors.Definitions;
using Zentient.Abstractions.Metadata;
using Zentient.Abstractions.Metadata.Readers;
using Zentient.Abstractions.Relations;
using Zentient.Abstractions.Relations.Definitions;

";

        protected override string GetCompliantImplementations(string ns, string baseName)
            => AbstractionStubs.All + Common.GetCompliantImplementations(ns) + Results.GetCompliantImplementations(ns, baseName);
    }
}
